"""update recipe model

Revision ID: 063af4cbb711
Revises: e992fd22a665
Create Date: 2023-02-17 12:27:27.446014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063af4cbb711'
down_revision = 'e992fd22a665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('picture_url', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('content', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('content')
        batch_op.drop_column('picture_url')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
