"""create recipe model

Revision ID: e992fd22a665
Revises: 
Create Date: 2023-02-15 13:48:18.004438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e992fd22a665'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('kcal', sa.Integer(), nullable=True),
    sa.Column('carbs', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('protein', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fat', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    # ### end Alembic commands ###
